# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJAcCXSBNEQidHX2Hoauy1SCHM2JGt6O
"""

import pandas as pd
import numpy as np

"""# Tải dữ liệu xét tuyển đại học"""

df = pd.read_csv('dulieuxettuyendaihoc.csv', index_col="STT")
df.head(10)

#Thống kê dữ liệu thiếu cho cột dân tộc và hiệu chỉnh dữ liệu thiếu như sau: Mặc định thiếu thì điền giá trị
df["DT"].fillna(0, inplace=True)
df.head(10)

#Thống kê dữ liệu thiếu cho biến T1 và hiệu chỉnh dữ liệu, lưu ý việc thay thế dữ liệu thiếu sử dụng phương pháp Mean
df['T1'].fillna(df['T1'].mean(), inplace=True)
df.head(10)

#Hãy thực hiện xử lý lần lượt tất cả dữ liệu thiếu cho các biến về điểm số còn lại
score_cols = [col for col in df.columns if col[0] in ['T','L','H','S','V','X','D','N','D']]

df[score_cols] = df[score_cols].apply(lambda x: x.fillna(x.mean()))
df

#Tạo các biến TBM1, TBM2, TBM3 tương ứng với trung bình môn của các năm lớp 10, 11 và 12.
#Công thức tính: TBM = (T*2 + L + H + S + V*2 + X + D + N) / 10
# Lớp 10
df['TBM1'] = (df['T1']*2 + df['L1'] + df['H1'] + df['S1'] +
              df['V1']*2 + df['X1'] + df['D1'] + df['N1']) / 10

# Lớp 11
df['TBM2'] = (df['T2']*2 + df['L2'] + df['H2'] + df['S2'] +
              df['V2']*2 + df['X2'] + df['D2'] + df['N2']) / 10

# Lớp 12
df['TBM3'] = (df['T6']*2 + df['L6'] + df['H6'] + df['S6'] +
              df['V6']*2 + df['X6'] + df['D6'] + df['N6']) / 10
df

#Tạo các biến xếp loại XL1, XL2 và XL3 dựa trên TBM1,TBM2 và TBM3 cho từng năm lớp 10, 11, 12 như sau:
#Nhỏ hơn 5.0 xếp loại: yếu (kí hiệu là Y)
#Từ 5.0 đến dưới 6.5: trung bình (kí hiệu là TB)
#Từ 6.5 đến dưới 8.0: khá (kí hiệu là K)
#Từ 8.0 đến dưới 9.0: giỏi (kí hiệu là G)
#Từ 9.0 trở lên: xuất sắc (kí hiệu là XS)
def xep_loai(tbm):
    if tbm < 5.0:
        return 'Y'
    elif tbm < 6.5:
        return 'TB'
    elif tbm < 8.0:
        return 'K'
    elif tbm < 9.0:
        return 'G'
    else:
        return 'XS'

df['XL1'] = df['TBM1'].apply(xep_loai)
df['XL2'] = df['TBM2'].apply(xep_loai)
df['XL3'] = df['TBM3'].apply(xep_loai)
df

#Tạo các biến US_TBM1, US_TBM2 và US_TBM3 để chuyển điểm trung bình các năm lớp 10, 11 và 12 từ thang điểm 10 của Việt Nam sang thang điểm 4 của Mỹ. Sử dụng phương pháp Min-Max Normalization
def min_max_to_4(x):
    return (x - x.min()) / (x.max() - x.min()) * 4

df['US_TBM1'] = min_max_to_4(df['TBM1'])
df['US_TBM2'] = min_max_to_4(df['TBM2'])
df['US_TBM3'] = min_max_to_4(df['TBM3'])
df

#Tạo biến kết quả xét tuyển (kí hiệu là KQXT) nhằm xác định sinh viên đậu (giá trị “1”) và rớt ( giá trị “0”) vào các khối dựa trên điểm DH1, DH2 và DH3 như sau
#Với khối A, A1 nếu [(DH1*2 + DH2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt
#Với khối B nếu [(DH1 + DH2*2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt
#Với khối khác nếu [(DH1+ DH2 + DH3)/3] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt
def ket_qua_xt(row):
    if row['KT'] in ['A', 'A1']:
        score = (row['DH1']*2 + row['DH2'] + row['DH3']) / 4
    elif row['KT'] == 'B':
        score = (row['DH1'] + row['DH2']*2 + row['DH3']) / 4
    else:
        score = (row['DH1'] + row['DH2'] + row['DH3']) / 3

    return 1 if score >= 5.0 else 0

df['KQXT'] = df.apply(ket_qua_xt, axis=1)
df

#11. Lưu trữ dữ liệu xuống ổ đĩa thành file processed_dulieuxettuyendaihoc.csv
df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)
df